extends: default

rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  comments-indentation: disable
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

ignore: |
  node_modules/
  .git/
  build/
  dist/
  target/
  .pytest_cache/
  __pycache__/
