[package]
name = "ruuvi-decoder"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
hex = "0.4.3"
structure = "0.1.2"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
rstest = "0.25.0"
serde_json = "1.0.140"
