[package]
name = "api"
version = "0.1.0"
edition = "2021"
resolver = "2"
description = "REST HTTP / WebSocket API for Ruuvi Home"
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
axum = { version = "0.8.4", features = ["macros"] }
serde.workspace = true
serde_json.workspace = true

chrono = { version = "0.4", features = ["serde"] }
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
postgres-store = { path = "../postgres-store" }
tower-http = { version = "0.6.4", features = ["cors"] }

[dev-dependencies]
axum-test = "17.3.0"
http-body-util = "0.1"
tower = { version = "0.5", features = ["util"] }
sqlx = { version = "0.8.6", features = [
  "runtime-tokio-rustls",
  "postgres",
  "chrono",
  "uuid",
] }
testcontainers = "0.24"
testcontainers-modules = { version = "0.12", features = ["postgres"] }
uuid = { version = "1.17", features = ["v4"] }
rstest = "0.25"
tempfile = "3.20"
tokio-test = "0.4"

[lints]
workspace = true
