[package]
name = "redis-store"
version = "0.1.0"
edition = "2021"
description = "Redis-based time-series storage with pub/sub for Ruuvi sensor data"
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono = { version = "0.4", features = ["serde"] }
redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }
uuid = { version = "1.10", features = ["v4"] }
