[package]
name = "influxdb-ruuvi-event"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
influxdb2 = { version = "0.5.2", default-features = false, features = [
  "rustls",
  "gzip",
] }
influxdb2-structmap = "0.2.0"
influxdb2-derive = "0.1.1"
num-traits = "0.2"
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.20"
rstest = "0.25"
uuid = { version = "1.17", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }

[lints]
workspace = true
